apiVersion: v1
kind: ConfigMap
metadata:
  name: master-map
data:
  CONFIG_SERVER_URL: "http://config-server-service:8081"
  KAFKA_K8S_CONFIG_URL: "kafka-service:9092"
  EUREKA_SERVER_HOSTNAME: "discovery-service"
  PULSAR_K8S_HOSTNAME: "pulsar-service"
  MONGO_K8S_HOSTNAME: "mongo-service"
  POSTGRES_K8S_HOSTNAME: "pg-service"
  MINIO_K8S_HOSTNAME: "minio-service"
  GATEWAY_K8S_HOSTNAME: "backend-service"

  # postgres
  POSTGRES_DB: "event"

  # zookeeper
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
---
# kafka
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092,PLAINTEXT_INTERNAL://kafka-service:29092"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT_INTERNAL"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
