# only for play-with-k8, in local no need to create pv's as minikube or other will take case by default

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /tmp/play-with-k8s-pv-mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /tmp/play-with-k8s-pv-pg
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /tmp/play-with-k8s-pv-zk
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /tmp/play-with-k8s-pv-kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/play-with-k8s-pv-minio
