---
# identity-service secrets(google, github, jwt)
apiVersion: v1
kind: Secret
metadata:
  name: identity-secrets
type: Opaque
data:
  JWT_SECRET_KEY: aGVsbG8tbXItc2VjcmV0LWtleS13aWxsLW5vdC1iZS11c2VkLWluLXByb2R1Y3Rpb24=  # hello-mr-secret-key-will-not-be-used-in-production
  GOOGLE_OAUTH2_CLIENT_ID: eHh4eHh4eA== #xxxxxxx
  GOOGLE_OAUTH2_CLIENT_SECRET: eHh4eHh4eA== #xxxxxxx
  GITHUB_OAUTH2_CLIENT_ID: eHh4eHh4eA== #xxxxxxx
  GITHUB_OAUTH2_CLIENT_SECRET: eHh4eHh4eA== #xxxxxxx

---
# payment-service secrets(razorpay)

apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
data:
  RAZOR_PAY_ID: eHh4eHh4eA== #xxxxxxx
  RAZOR_PAY_SECRET: eHh4eHh4eA== #xxxxxxx

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
data:
  MINIO_ROOT_USER: bWluaW8xMjM0  # minio1234
  MINIO_ROOT_PASSWORD: bWluaW8xMjM0  # minio1234

  MINIO_ACCESS_KEY: bWluaW8xMjM0 # minio1234
  MINIO_SECRET_KEY: bWluaW8xMjM0 # minio1234

---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secrets
data:
  POSTGRES_USER: ZXZlbnQ=  # event
  POSTGRES_PASSWORD: ZXZlbnQ=  # event
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-secrets
data:
  GMAIL_ID: eHh4eHh4eA== #xxxxxxx
  GMAIL_APP_PASSWORD: eHh4eHh4eA== #xxxxxxx