name: event-booking-application

services:
  mongodb:
    container_name: event_mongo
    image: mongo
    networks:
      - event-booking-network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: event
      MONGO_INITDB_ROOT_PASSWORD: event
    volumes:
      - event_mongo:/data
    restart: unless-stopped
networks:
  event-booking-network:
    driver: bridge

volumes:
  event_mongo: