application:
  mode: dev
  server:
    # gateway server port
    port: 8080
  config:
    eureka:
      port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${application.config.eureka.port}/eureka
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}

# let it be for all. will ignore if not using openfeign
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false
