application:
  server:
    # gateway server port
    port: 8080
  config:
    eureka:
      port: 8082

# jwt secret key for token generation
#  security:
#    jwt-secret-key: adfasd

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${application.config.eureka.port}/eureka
  instance:
    hostname: localhost

# let it be for all. will ignore if not using openfeign
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false