application:
  mode: dev
  server:
    # gateway server port
    port: 8080
  config:
    eureka:
      port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME:localhost}:${application.config.eureka.port}/eureka
  instance:
    hostname: localhost


# let it be for all. will ignore if not using openfeign
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false
    kubernetes:
      discovery:
        enabled: false
      config:
        enabled: false