spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: true

application:
  server:
    # gateway server port
    port: 8080
  config:
    eureka:
      port: 8082

# jwt secret key for token generation
#  security:
#    jwt-secret-key: adfasd

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${application.config.eureka.port}/eureka
  instance:
    hostname: localhost
