spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: true

  data:
    mongodb:
      database: event-core
      host: localhost
      port: 27017
server:
  port: 8083
