spring:
  data:
    mongodb:
      username: event
      password: event
      database: event-catalog
      host: localhost
      port: 27017
      authentication-database: admin
server:
  port: 8083
