spring:
  data:
    mongodb:
      username: event
      password: event
      database: event-catalog
      host: localhost
      port: 27017
      authentication-database: admin
  webflux:
    base-path: /event-catalog
server:
  port: 8083
