spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_K8S_HOSTNAME:localhost}:5432/identity
    username: ${POSTGRES_USER:event}
    password: ${POSTGRES_PASSWORD:event}
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            redirect-uri: "http://${GATEWAY_K8S_HOSTNAME:localhost}:8080/login/oauth2/code/google"
            scope:
              - profile
              - email
          github:
            client-id: ${GITHUB_OAUTH2_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH2_CLIENT_SECRET}
            redirect-uri: "http://${GATEWAY_K8S_HOSTNAME:localhost}:8080/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: read:user, user:email

        provider:
          google:
            user-name-attribute: email
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
application:
  security:
    jwt-secret-key: ${JWT_SECRET_KEY:hello-mr-secret-key-will-not-be-used-in-production}
server:
  port: 8084
