spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_K8S_HOSTNAME:localhost}:5432/orders
    username: ${POSTGRES_USER:event}
    password: ${POSTGRES_PASSWORD:event}

server:
  port: 8086
