spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_K8S_HOSTNAME:localhost}:5432/payments
    username: ${POSTGRES_USER:event}
    password: ${POSTGRES_PASSWORD:event}

server:
  port: 8087
razorpay:
  key:
    id: ${RAZOR_PAY_ID}
    secret: ${RAZOR_PAY_SECRET}
