spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: event
    password: event

server:
  port: 8087
razorpay:
  key:
    id: ${RAZOR_PAY_ID}
    secret: ${RAZOR_PAY_SECRET}
