apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: config-server-deployment
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: ppk4/event-booking-config-server
          ports:
            - containerPort: 8081
              name: api
          readinessProbe:
            httpGet:
              port: api
              path: /actuator/health/readiness
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: api
              path: /actuator/health/liveness
            initialDelaySeconds: 5
            periodSeconds: 10