apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  labels:
    app: discovery-deployment
spec:
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery-container
          image: localhost:5000/discovery
          ports:
            - containerPort: 8082
              name: api
          envFrom:
            - configMapRef:
                name: master-map
          livenessProbe:
            httpGet:
              port: api
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: api
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 10