apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  labels:
    app: discovery-deployment
spec:
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery-container
          image: localhost:5000/discovery
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: CONFIG_SERVER_URL
                  name: master-map
            - name: EUREKA_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: EUREKA_HOSTNAME
                  name: master-map