apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-core-deployment
  labels:
    app: event-core-deployment
spec:
  selector:
    matchLabels:
      app: event-core
  template:
    metadata:
      labels:
        app: event-core

    spec:
      containers:
        - name: event-core-container
          image: localhost:5000/event-core
          ports:
            - containerPort: 8083
              name: event-core
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: event-core-service
          envFrom:
            - configMapRef:
                name: master-map
          readinessProbe:
            httpGet:
              port: 8083
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8083
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 10