apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  labels:
    app: gateway-service-deployment
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    spec:
      containers:
        - name: gateway-container
          image: localhost:5000/gateway
          ports:
            - containerPort: 8080