name: Maven CI


on:
  push:
    branches:
      - "master"
jobs:
  test:
    strategy:
      matrix:
        project-folder: [ "config-server", "event-catalog", "identity", "event-core"]
    name: Install and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21
      - name: Maven Install
        run: mvn clean verify -pl ${{matrix.project-folder}} -am --no-transfer-progress
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{matrix.project-folder}}/target/site/jacoco
          name: coverage-report-${{matrix.project-folder}}
